### ISSUE TITLE
compiling this repository

### ISSUE THREAD

**Issue by ekm507** [tschnz/Live-Video-Magnification#12]
Hi!
I am trying to compile this code but I don't know how to!
could you please help me?
there is not enough information for compiling on README.md

I also would very appreciate it if you send me an email.

**Comment by nincube8** [comment]
You have to modify the QT library to match the paths of your machine, and
your installation of OpenCV and QT Creator. In python it has to be set up
under a virtual shell environment.
OpenCV libraries have to match the your python version, and the processor
your machine uses to successfully compile. Once you successfully compile
it, you can use QT creator to compile and run the program on each startup.

**Comment by nincube8** [comment]
There is a file called RVM pro. That file has to be modified using the
paths that match your machines paths. OpenCV, Ect. Match them to where your
directories are installed. You may need Visual Studio to generate a
solution file. .so File.

**Comment by nincube8** [comment]
There is a program that will generate the solution file if you have OpenCV
you can specify your machine's parameters if you load the solution file in
it.
Hope this helps.

**Comment by PeterSinelnikov** [comment]
For those who have problems with compiling this repository under Windows. I come from Java and Python background, so compiling C++/Qt code was something completely new to me. After fussing with it for a couple of days I finally got it to work:

- install the older version of Qt (5.15) instead of what comes out of the box with the installer(6.xx). Make sure to use MSVC option for building instead of MinGW or whatever else.
- edit all the paths in .pro file like already mentioned by others here (I use OpenCV 4.6.0)
![image](https://github.com/user-attachments/assets/b7beaf54-b184-4087-a990-104d2476d2ac)

**Comment by tschnz** [comment]
Hey this is changed to use CMake, supports Qt6 and OpenCV4x. If errors persist please open a new issue / PR
